CREATE TABLE [dbo].[Attestations]
(
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TeacherId UNIQUEIDENTIFIER NOT NULL,
    GroupId UNIQUEIDENTIFIER NOT NULL,
    CurriculumUnitId UNIQUEIDENTIFIER NOT NULL,
    Date DATETIME NOT NULL
)
