CREATE TABLE [dbo].[CurriculumUnits]
(
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    SpecialityId UNIQUEIDENTIFIER NOT NULL,
    Semester INT NOT NULL,
    SubjectId UNIQUEIDENTIFIER NOT NULL,
    WorkTypeId UNIQUEIDENTIFIER NOT NULL,
    Name NVARCHAR(75) NOT NULL,
)
