CREATE TABLE [dbo].[CurriculumUnits]
(
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    SpecialityId UNIQUEIDENTIFIER NOT NULL,
    Cource INT NOT NULL,
    SubjectId UNIQUEIDENTIFIER NOT NULL,
    Type INT NOT NULL
)
