CREATE TABLE [dbo].[Groups]
(
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(255) NOT NULL,
    Cource INT NOT NULL,
    SpecialityId UNIQUEIDENTIFIER NOT NULL,
    FOREIGN KEY (SpecialityId) REFERENCES Specialities(Id)
)
