CREATE TABLE [dbo].[Specialities]
(
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    ShortName NVARCHAR(255) NOT NULL,
    FullName NVARCHAR(255) NOT NULL,
    FacultyId UNIQUEIDENTIFIER NOT NULL,
    FOREIGN KEY (FacultyId) REFERENCES Faculties(Id)
)
